server:
  port: 8081

spring:
  application:
    name: spring-cloud-config-server  # 应用名称，后面会在服务消费者中用到
  cloud:
    config:
      server:
        git:
          uri: https://github.com/puppylpg/spring-cloud-config-center #配置文件所在仓库
          username: puppylpg
          password: *******
          default-label: master #配置文件分支
          search-paths: pokemon  #配置文件所在根目录

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka  ## 注册到 eureka
    register-with-eureka: true
    fetch-registry: true
